### ISSUE TITLE
Making Accessible Graphs

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/Foxlights#11]
https://github.com/LaraVolski/Foxlights/blob/94441ba41ea17d902fcbd6cabf7cf909c4aa09cf/foxlights_data_analysis.Rmd#L281

Hi Kaitlyn!

Frontiers recommends  that we avoid using only color to communicate information in order to help with accessibility and using patterns instead. Do you have recommendations for how to go about doing that with this graph?

Thanks much!
Lara

**Comment by kaitlyngaynor** [comment]
I would use multiple line types—so, change where you have linetype = c(1,1)

1 = solid, 2 = dashed, 3 = dotted etc see links:

http://www.sthda.com/english/wiki/ggplot2-line-types-how-to-change-line-types-of-a-graph-in-r-software
http://www.sthda.com/english/wiki/line-types-in-r-lty

**Comment by kaitlyngaynor** [comment]
so changing it to linetype = c(1,2), linecol = c("palegreen4", "darkorange4")... will result in a solid green line and a dashed orange line. let me know if you run into trouble implementing this!

**Comment by LaraVolski** [comment]
That was easy -- thanks Kaitlyn!
