### ISSUE TITLE
Adding digits to null + ruggedness.25 model (line 178)

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/Foxlights#7]
https://github.com/LaraVolski/Foxlights/blob/712894b97b2e4a000268bb2ee56ff0a13ef04a74/foxlight_model_selection.Rmd#L114

Hi Kaitlyn! Would you mind double checking that I did this correctly? I'm getting a weird error message.

**Comment by kaitlyngaynor** [comment]
Not sure of your goal, but you are referencing the fit8 object within the function that creates the fit8 object so that's your problem/error. I pulled out the print(fit8) function outside and now there is no error. Does that solve it?

**Comment by kaitlyngaynor** [comment]
I made the changes so just pull em :)

**Comment by LaraVolski** [comment]
Thank you!!
